server:
  port: 30004
spring:
  application:
    name: spshot-quartz
  redis:
    host: localhost
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    # 应用关闭时，是否等待定时任务执行完成。默认为 false
    wait-for-jobs-to-complete-on-shutdown: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: localhost
ftp:
  config:
    host: xxxx
    port: 21
    username: xxxx
    password: xxxx
weixin:
  config:
    appid: xxxx
    secret: xxxx
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000 # 熔断超时时长：60000ms
